_common/lib: !include "../package-lib.yaml"

name: stellar-sdk-client
version: 0.1.0.0
<<: *meta
<<: *defaults

executables:
  stellar-client:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens
    - newtype
    - stellar-sdk-core
    - stellar-sdk-client
    - refined
    - text
    - haskeline

library:
  source-dirs: src
  dependencies:
    - aeson
    - binary
    - bytestring
    - base64-bytestring
    - exceptions
    - extra
    - http-api-data
    - http-conduit
    - http-types
    - lens
    - network-uri
    - mtl
    - named
    - newtype
    - stellar-sdk-core
    - text
    - transformers
    - transformers-lift
  exposed-modules:
    - Control.Monad.Rest
    - Control.Monad.Trans.Rest
    - Control.Monad.Stellar
    - Control.Monad.Trans.Stellar
    - Stellar.Client
    - Stellar.Client.Lenses
    - Stellar.Parser
    - Stellar.Printer
