name: stellar-client
version: 0.1.0.0
author: DSQ AG
maintainer: engineering@dstoq.exchange
copyright: DSQ AG
github: dstoq/haskell-stellar-core

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wimplicit-prelude
- -Wtabs
- -Wmissing-local-signatures
- -fhelpful-errors
- -fprint-expanded-synonyms

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns

executables:
  stellar-client:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.9 && < 5
    - lens
    - newtype
    - stellar-core
    - stellar-client
    - protolude
    - refined
    - text
    - haskeline

library:
  source-dirs: src
  dependencies:
    - aeson
    - base >= 4.9 && < 5
    - binary
    - bytestring
    - base64-bytestring
    - exceptions
    - extra
    - http-api-data
    - http-conduit
    - http-types
    - lens
    - network-uri
    - mtl
    - named
    - newtype
    - protolude
    - stellar-core
    - text
    - transformers
    - transformers-lift
  exposed-modules:
    - Control.Monad.Rest
    - Control.Monad.Trans.Rest
    - Control.Monad.Stellar
    - Control.Monad.Trans.Stellar
    - Stellar.Client
    - Stellar.Client.Lenses
    - Stellar.Parser
    - Stellar.Printer
