_common/lib: !include "../package-lib.yaml"

name: stellar-sdk-hedgehog-generators
version: 0.1.0.0
<<: *meta
<<: *defaults

library:
  source-dirs: src
  dependencies:
  - base >= 4.9 && < 5
  - binary
  - cryptonite
  - protolude
  - hedgehog
  - newtype
  - refined
  - stellar-sdk-core
  - stellar-sdk-client
  - static-text
  exposed-modules:
  - Stellar.Gens
