name: stellar-core-generators
version: 0.1.0.0
author: DSQ AG
maintainer: engineering@dstoq.exchange
copyright: DSQ AG
github: dstoq/haskell-stellar-core

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wimplicit-prelude
- -Wtabs
- -Wmissing-local-signatures
- -fhelpful-errors
- -fprint-expanded-synonyms

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

library:
  source-dirs: src
  dependencies:
  - base >= 4.9 && < 5
  - binary
  - cryptonite
  - protolude
  - hedgehog
  - newtype
  - refined
  - stellar-core
  - static-text
  exposed-modules:
  - Stellar.Gens
